<?php
declare(strict_types=1);
namespace App\Core;

class Config
{
    protected static array $config = [];
    protected static bool $loaded = false;

    /**
     * Load all PHP config files from config folder.
     * If a cached config exists (generated by ConfigCache::cache()), it is used instead.
     *
     * @param string $configPath
     * @return void
     */
    public static function load(string $configPath): void
    {
        if (self::$loaded) {
            return;
        }

        // Check for pre-compiled cache first
        $cache = new \App\Core\ConfigCache();
        if ($cache::hasCache()) {
            $cached = require $cache::getPath();
            if (is_array($cached)) {
                self::$config = $cached;
                self::$loaded = true;
                return;
            }
        }

        $files = glob(rtrim($configPath, '/') . '/*.php');

        foreach ($files as $file) {
            $key = basename($file, '.php');
            $config = require $file;
            if (is_array($config)) {
                self::$config[$key] = $config;
            }
        }

        self::$loaded = true;
    }

    /**
     * Get config value by dot notation key, fallback to $_ENV if not found.
     *
     * @param string $key
     * @param mixed $default
     * @return mixed
     */
    public static function get(string $key, $default = null)
    {
        if (!self::$loaded) {
            throw new \Exception('Config not loaded. Call Config::load() first.');
        }

        $keys = explode('.', $key);
        $value = self::$config;

        foreach ($keys as $k) {
            if (!isset($value[$k])) {
                // Fallback to environment variables (strtoupper + underscores)
                $envKey = strtoupper(str_replace('.', '_', $key));
    
                return env($envKey, $default);
            }
            $value = $value[$k];
        }
        
        return $value;
    }
}
